# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
resources:
  containers:
    - container: 'sqlserver_linux_container_for_integration_tests'
      image: 'mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04'
      ports:
        - 1433:1433/tcp
      env:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: 'StrongPassword905'

trigger:
- main

pr: none

pool:
  vmImage: 'ubuntu-18.04'

variables:
  dotnetSdkVersion: '3.1.300'
  buildPlatform: 'Any CPU'
  
services:
  sqlserver_linux_container_for_integration_tests: sqlserver_linux_container_for_integration_tests
  
steps:
  - task: UseDotNet@2
    displayName: 'Use .Net Core SDK $(dotnetSdkVersion)'
    inputs:
      version: '$(dotnetSdkVersion)'
  
  - task: DotNetCoreCLI@2
    displayName: 'New manifest for tool'
    inputs:
      command: custom
      custom: 'new'
      arguments: tool-manifest
  - task: DotNetCoreCLI@2
    displayName: 'Install EF Tool'
    inputs:
      command: custom
      custom: 'tool'
      arguments: install dotnet-ef
      
  - task: DotNetCoreCLI@2
    displayName: 'Restore project dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build the test project'
    inputs:
      command: 'build'
      arguments: '--no-restore'
      projects: 'TramsDataApi.Test/*.csproj'
  
  - task: DotNetCoreCLI@2
    displayName: 'Create migrations for test db'
    inputs:
      command: custom
      custom: 'ef'
      arguments: 'migrations add CreateForTests'
      workingDirectory: TramsDataApi

  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: 'test'
      publishTestResults: true
      projects: '**/*.Test.csproj'

  
  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      arguments: '--output $(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'tramsApiBuild'
      publishLocation: 'Container'