version: "3.8"
services:
  zap:
    container_name: zap
    image: owasp/zap2docker-stable:2.11.1 # pinned until alpn config issue is resolved - https://github.com/zaproxy/zaproxy/issues/7699
    command: "zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true"
    ports:
      - 8080:8080
    user: zap
  cypress:
    build:
      context: ./CypressTests
      dockerfile: Dockerfile
    command: -- --env apiKey=<api-key>,url=<url>,zapReport=true
    depends_on:
      zap:
        condition: service_healthy
    env_file:
      - ./CypressTests/.env
    volumes:
      - ./zap:/reports

# Command to use to ensure compose closes on test finishes
# docker compose up --exit-code-from cypress