// <auto-generated />
using System;
using Dfe.Academies.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dfe.Academies.Infrastructure.Migrations.EdPerf
{
    [DbContext(typeof(EdperfContext))]
    partial class EdperfContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dfe.Academies.Domain.EducationalPerformance.SchoolAbsence", b =>
                {
                    b.Property<string>("DownloadYear")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("URN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ESTAB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("DateAndTimeImported")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PERCTOT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PPERSABS10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DownloadYear", "URN", "LA", "ESTAB");

                    b.ToTable("download_PUPILABSENCE_england_ALL", "edperf");
                });
#pragma warning restore 612, 618
        }
    }
}
