// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TramsDataApi.DatabaseModels;

namespace TramsDataApi.Migrations.TramsDb
{
    [DbContext(typeof(TramsDbContext))]
    [Migration("20211130165933_ChangeA2BApplicationStatusIdColumnToInt")]
    partial class ChangeA2BApplicationStatusIdColumnToInt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.AcademyTransferProjectUrns", "'AcademyTransferProjectUrns', '', '10000000', '1', '10000000', '', 'Int32', 'False'")
                .HasAnnotation("Relational:Sequence:.ConcernsGlobalSequence", "'ConcernsGlobalSequence', '', '1', '1', '1', '', 'Int32', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationLeadAuthorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationLeadAuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationRoleOtherDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ApplicationSubmitted")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChangesToLaGovernance")
                        .HasColumnType("int");

                    b.Property<string>("ChangesToLaGovernanceExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChangesToTrust")
                        .HasColumnType("int");

                    b.Property<string>("ChangesToTrustExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FormTrustGrowthPlansYesNo")
                        .HasColumnType("int");

                    b.Property<string>("FormTrustImprovementApprovedSponsor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustImprovementStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustImprovementSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FormTrustOpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormTrustPlanForGrowth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustPlansForNoGrowth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustProposedNameOfTrust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FormTrustReasonApprovalToConvertAsSat")
                        .HasColumnType("int");

                    b.Property<string>("FormTrustReasonApprovedPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonForming")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonFreedom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonGeoAreas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonImproveTeaching")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonVision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustApproverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustApproverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationId");

                    b.ToTable("A2BApplication","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplicationKeyPersons", b =>
                {
                    b.Property<int>("KeyPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KeyPersonBiography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPersonCeoExecutive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPersonChairOfTrust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPersonDateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPersonFinancialDirector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPersonFinancialDirectorTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPersonMember")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPersonOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyPersonTrustee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyPersonId");

                    b.ToTable("A2BApplicationKeyPersons","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplicationStatus", b =>
                {
                    b.Property<int>("ApplicationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationStatusId");

                    b.ToTable("A2BApplicationStatus","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplyingSchool", b =>
                {
                    b.Property<string>("ApplyingSchoolsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolAdEqualitiesImpactAssessment")
                        .HasColumnType("int");

                    b.Property<string>("SchoolAdFeederSchools")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolAdInspectedButReportNotPublished")
                        .HasColumnType("int");

                    b.Property<string>("SchoolAdInspectedReportNotPublishedExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolAdSafeguarding")
                        .HasColumnType("int");

                    b.Property<string>("SchoolAdSafeguardingExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolAdSchoolContributionToTrust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolAddFurtherInformation")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolBuildLandFutureProgramme")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolBuildLandGrants")
                        .HasColumnType("int");

                    b.Property<string>("SchoolBuildLandGrantsBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolBuildLandOwnerExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolBuildLandPFIScheme")
                        .HasColumnType("int");

                    b.Property<string>("SchoolBuildLandPFISchemeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolBuildLandPriorityBuildingProgramme")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolBuildLandSharedFacilities")
                        .HasColumnType("int");

                    b.Property<string>("SchoolBuildLandSharedFacilitiesExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolBuildLandWorksPlanned")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SchoolBuildLandWorksPlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchoolBuildLandWorksPlannedExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SchoolCFYCapitalForward")
                        .HasColumnType("float");

                    b.Property<int?>("SchoolCFYCapitalForwardStatus")
                        .HasColumnType("int");

                    b.Property<string>("SchoolCFYCapitalForwardStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SchoolCFYEndDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SchoolCFYRevenue")
                        .HasColumnType("float");

                    b.Property<int?>("SchoolCFYRevenueStatus")
                        .HasColumnType("int");

                    b.Property<string>("SchoolCFYRevenueStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolCapacityAssumptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolCapacityPublishedAdmissionsNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolCapacityYear1")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolCapacityYear2")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolCapacityYear3")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolConsultationStakeholders")
                        .HasColumnType("int");

                    b.Property<string>("SchoolConsultationStakeholdersConsult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionApproverContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionApproverContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolConversionChangeName")
                        .HasColumnType("int");

                    b.Property<string>("SchoolConversionChangeNameValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactChairEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactChairName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactChairTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactHeadEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactHeadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactHeadTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolConversionMainContact")
                        .HasColumnType("int");

                    b.Property<string>("SchoolConversionMainContactOtherEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionMainContactOtherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionMainContactOtherRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionMainContactOtherTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionReasonsForJoining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SchoolConversionTargetDateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SchoolConversionTargetDateDifferent")
                        .HasColumnType("int");

                    b.Property<string>("SchoolConversionTargetDateExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolDeclarationBodyAgree")
                        .HasColumnType("int");

                    b.Property<string>("SchoolDeclarationSignedByEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolDeclarationSignedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolDeclarationSignedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolDeclarationTeacherChair")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolFaithSchool")
                        .HasColumnType("int");

                    b.Property<string>("SchoolFaithSchoolDioceseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolFinancialInvestigations")
                        .HasColumnType("int");

                    b.Property<string>("SchoolFinancialInvestigationsExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolFinancialInvestigationsTrustAware")
                        .HasColumnType("int");

                    b.Property<string>("SchoolFurtherInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolLaClosurePlans")
                        .HasColumnType("int");

                    b.Property<string>("SchoolLaClosurePlansExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolLaReorganization")
                        .HasColumnType("int");

                    b.Property<string>("SchoolLaReorganizationExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolLeaseExists")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolLoanExists")
                        .HasColumnType("int");

                    b.Property<double?>("SchoolNFYCapitalForward")
                        .HasColumnType("float");

                    b.Property<int?>("SchoolNFYCapitalForwardStatus")
                        .HasColumnType("int");

                    b.Property<string>("SchoolNFYCapitalForwardStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SchoolNFYEndDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SchoolNFYRevenue")
                        .HasColumnType("float");

                    b.Property<int?>("SchoolNFYRevenueStatus")
                        .HasColumnType("int");

                    b.Property<string>("SchoolNFYRevenueStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SchoolPFYCapitalForward")
                        .HasColumnType("float");

                    b.Property<int?>("SchoolPFYCapitalForwardStatus")
                        .HasColumnType("int");

                    b.Property<string>("SchoolPFYCapitalForwardStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SchoolPFYEndDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("SchoolPFYRevenue")
                        .HasColumnType("float");

                    b.Property<int?>("SchoolPFYRevenueStatus")
                        .HasColumnType("int");

                    b.Property<string>("SchoolPFYRevenueStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolPartOfFederation")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolSACREExemption")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SchoolSACREExemptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SchoolSupportGrantFundsPaidTo")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolSupportedFoundation")
                        .HasColumnType("int");

                    b.Property<string>("SchoolSupportedFoundationBodyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedSchoolFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedTrustFields")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplyingSchoolsId");

                    b.ToTable("A2BApplyingSchool","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BContributor", b =>
                {
                    b.Property<string>("ContributorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationTypeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContributorAppIdTest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContributorUserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContributorUserId");

                    b.ToTable("A2BContributor","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BCreateSchoolRequest", b =>
                {
                    b.Property<string>("SchoolId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolId");

                    b.ToTable("A2BCreateSchoolRequest","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BSchoolLease", b =>
                {
                    b.Property<string>("SchoolLeaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SchoolLeaseInterestRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLeasePaymentToDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLeasePurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLeaseRepaymentValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLeaseResponsibleForAssets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLeaseTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLeaseValueOfAssets")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolLeaseId");

                    b.ToTable("A2BSchoolLease","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BSchoolLoan", b =>
                {
                    b.Property<string>("SchoolLoanId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SchoolLoanAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLoanInterestRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLoanProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLoanPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLoanSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolLoanId");

                    b.ToTable("A2BSchoolLoan","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyConversionProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcademyOrderRequired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcademyTypeAndRoute")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActualPupilNumbers")
                        .HasColumnType("int");

                    b.Property<string>("AgeRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApplicationReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicationReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BaselineDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int");

                    b.Property<decimal?>("CapitalCarryForwardAtEndMarchCurrentYear")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<decimal?>("CapitalCarryForwardAtEndMarchNextYear")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<string>("ClearedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConversionSupportGrantAmount")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<string>("ConversionSupportGrantChangeReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiocesanTrust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DistanceFromSchoolToTrustHeadquarters")
                        .HasColumnType("decimal(38, 3)");

                    b.Property<string>("DistanceFromSchoolToTrustHeadquartersAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EqualitiesImpactAssessmentConsidered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancialDeficit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GeneralInformationSectionComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HeadTeacherBoardDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IfdPipelineId")
                        .HasColumnType("int");

                    b.Property<string>("KeyStage2PerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyStage4PerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyStage5PerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalAuthorityInformationTemplateComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalAuthorityInformationTemplateLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LocalAuthorityInformationTemplateReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("LocalAuthorityInformationTemplateSectionComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LocalAuthorityInformationTemplateSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberOfParliamentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberOfParliamentParty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfTrust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartOfPfiScheme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PercentageFreeSchoolMeals")
                        .HasColumnType("decimal(38, 3)");

                    b.Property<decimal?>("PercentageOfGoodOrOutstandingSchoolsInTheDiocesanTrust")
                        .HasColumnType("decimal(38, 3)");

                    b.Property<DateTime?>("PreviousHeadTeacherBoardDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousHeadTeacherBoardDateQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousHeadTeacherBoardLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProjectedRevenueBalanceAtEndMarchNextYear")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<DateTime?>("ProposedAcademyOpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublishedAdmissionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RationaleForProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RationaleForTrust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RationaleSectionComplete")
                        .HasColumnType("bit");

                    b.Property<string>("RecommendationForProject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RevenueCarryForwardAtEndMarchCurrentYear")
                        .HasColumnType("decimal(38, 2)");

                    b.Property<string>("RisksAndIssues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RisksAndIssuesSectionComplete")
                        .HasColumnType("bit");

                    b.Property<bool?>("SchoolAndTrustInformationSectionComplete")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolBudgetInformationAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolBudgetInformationSectionComplete")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolPerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolPhase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolPupilForecastsAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SponsorReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Urn")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViabilityIssues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearOneProjectedCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("YearOneProjectedPupilNumbers")
                        .HasColumnType("int");

                    b.Property<int?>("YearThreeProjectedCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("YearThreeProjectedPupilNumbers")
                        .HasColumnType("int");

                    b.Property<int?>("YearTwoProjectedCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("YearTwoProjectedPupilNumbers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AcademyConversionProject","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyConversionProjectNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AcademyConversionProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AcademyConversionProjectId");

                    b.ToTable("AcademyConversionProjectNote","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyTransferProjectIntendedTransferBenefits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FkAcademyTransferProjectId")
                        .HasColumnName("fk_AcademyTransferProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedBenefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkAcademyTransferProjectId");

                    b.ToTable("AcademyTransferProjectIntendedTransferBenefits","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyTransferProjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcademyPerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComplexLandAndBuildingFurtherSpecification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ComplexLandAndBuildingShouldBeConsidered")
                        .HasColumnType("bit");

                    b.Property<string>("FinanceAndDebtFurtherSpecification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FinanceAndDebtShouldBeConsidered")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasHtbDate")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasTargetDateForTransfer")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasTransferFirstDiscussedDate")
                        .HasColumnType("bit");

                    b.Property<string>("HighProfileFurtherSpecification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HighProfileShouldBeConsidered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HtbDate")
                        .HasColumnType("date");

                    b.Property<string>("KeyStage2PerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyStage4PerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyStage5PerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestOfstedJudgementAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherBenefitValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherTransferTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutgoingTrustUkprn")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("ProjectRationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PupilNumbersAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RddOrEsfaIntervention")
                        .HasColumnType("bit");

                    b.Property<string>("RddOrEsfaInterventionDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDateForTransfer")
                        .HasColumnType("date");

                    b.Property<DateTime?>("TransferFirstDiscussed")
                        .HasColumnType("date");

                    b.Property<string>("TrustSponsorRationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfTransfer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR AcademyTransferProjectUrns");

                    b.Property<string>("WhoInitiatedTheTransfer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__AcademyT__C5B214360AF6201A");

                    b.HasIndex("Urn")
                        .HasName("AcademyTransferProjectUrn");

                    b.ToTable("AcademyTransferProjects","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.ConcernsCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CaseAim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrmEnquiry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeEscalation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeEscalationPoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirectionOfTravel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Issue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NextSteps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonAtReview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReviewAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusUrn")
                        .HasColumnType("int");

                    b.Property<string>("TrustUkprn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR ConcernsGlobalSequence");

                    b.HasKey("Id")
                        .HasName("PK__CCase__C5B214360AF620234");

                    b.ToTable("ConcernsCase","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.ConcernsRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR ConcernsGlobalSequence");

                    b.HasKey("Id")
                        .HasName("PK__CRating");

                    b.ToTable("ConcernsRating","sdd");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Red-Plus",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Red",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Red-Amber",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amber-Green",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "n/a",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        });
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.ConcernsRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReviewAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusUrn")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR ConcernsGlobalSequence");

                    b.HasKey("Id")
                        .HasName("PK__CRecord");

                    b.HasIndex("CaseId");

                    b.HasIndex("RatingId");

                    b.HasIndex("TypeId");

                    b.ToTable("ConcernsRecord","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.ConcernsStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR ConcernsGlobalSequence");

                    b.HasKey("Id")
                        .HasName("PK__CStatus__C5B214360AF620234");

                    b.ToTable("ConcernsStatus","sdd");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Live",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Monitoring",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Close",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        });
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.ConcernsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Urn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR ConcernsGlobalSequence");

                    b.HasKey("Id")
                        .HasName("PK__CType");

                    b.ToTable("ConcernsType","sdd");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Financial reporting",
                            Name = "Compliance",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Financial returns",
                            Name = "Compliance",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deficit",
                            Name = "Financial",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Projected deficit / Low future surplus",
                            Name = "Financial",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cash flow shortfall",
                            Name = "Financial",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Clawback",
                            Name = "Financial",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Force majeure",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Governance",
                            Name = "Governance",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Closure",
                            Name = "Governance",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Executive Pay",
                            Name = "Governance",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Safeguarding",
                            Name = "Governance",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Allegations and self reported concerns",
                            Name = "Irregularity",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Related party transactions - in year",
                            Name = "Irregularity",
                            UpdatedAt = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Urn = 0
                        });
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.TransferringAcademies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FkAcademyTransferProjectId")
                        .HasColumnName("fk_AcademyTransferProjectId")
                        .HasColumnType("int");

                    b.Property<string>("IncomingTrustUkprn")
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("OutgoingAcademyUkprn")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.HasIndex("FkAcademyTransferProjectId");

                    b.ToTable("TransferringAcademies","sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyConversionProjectNote", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.AcademyConversionProject", "AcademyConversionProject")
                        .WithMany()
                        .HasForeignKey("AcademyConversionProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyTransferProjectIntendedTransferBenefits", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.AcademyTransferProjects", "FkAcademyTransferProject")
                        .WithMany("AcademyTransferProjectIntendedTransferBenefits")
                        .HasForeignKey("FkAcademyTransferProjectId")
                        .HasConstraintName("FK__AcademyTr__fk_Ac__4316F928");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.ConcernsRecord", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.ConcernsCase", "ConcernsCase")
                        .WithMany("ConcernsRecords")
                        .HasForeignKey("CaseId")
                        .HasConstraintName("FK__ConcernsCase_ConcernsRecord")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TramsDataApi.DatabaseModels.ConcernsRating", "ConcernsRating")
                        .WithMany("FkConcernsRecord")
                        .HasForeignKey("RatingId")
                        .HasConstraintName("FK__ConcernsRecord_ConcernsRating")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TramsDataApi.DatabaseModels.ConcernsType", "ConcernsType")
                        .WithMany("FkConcernsRecord")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK__ConcernsRecord_ConcernsType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.TransferringAcademies", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.AcademyTransferProjects", "FkAcademyTransferProject")
                        .WithMany("TransferringAcademies")
                        .HasForeignKey("FkAcademyTransferProjectId")
                        .HasConstraintName("FK__Transferr__fk_Ac__403A8C7D");
                });
#pragma warning restore 612, 618
        }
    }
}
