// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TramsDataApi.DatabaseModels;

#nullable disable

namespace TramsDataApi.Migrations.TramsDb
{
    [DbContext(typeof(TramsDbContext))]
    [Migration("20230712114342_academy-transfer-project-urn_sdd_schema")]
    partial class academytransferprojecturn_sdd_schema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.HasSequence<int>("sequence_AcademyTransferProjectUrn", "sdd")
                .StartsAt(10003000L)
                .HasMin(10003000L);

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplication", b =>
                {
                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationLeadAuthorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationLeadAuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationLeadEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationRoleOtherDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationStatusId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ApplicationSubmitted")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ChangesToLaGovernance")
                        .HasColumnType("bit");

                    b.Property<string>("ChangesToLaGovernanceExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ChangesToTrust")
                        .HasColumnType("bit");

                    b.Property<string>("ChangesToTrustExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DynamicsApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("FormTrustGrowthPlansYesNo")
                        .HasColumnType("bit");

                    b.Property<string>("FormTrustImprovementApprovedSponsor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustImprovementStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustImprovementSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FormTrustOpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormTrustPlanForGrowth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustPlansForNoGrowth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustProposedNameOfTrust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FormTrustReasonApprovalToConvertAsSat")
                        .HasColumnType("bit");

                    b.Property<string>("FormTrustReasonApprovedPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonForming")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonFreedom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonGeoAreas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonImproveTeaching")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormTrustReasonVision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustApproverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustApproverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationId");

                    b.ToTable("A2BApplication", "sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplicationApplyingSchool", b =>
                {
                    b.Property<int>("ApplyingSchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplyingSchoolId"), 1L, 1);

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiocesePermissionEvidenceDocumentLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DynamicsApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DynamicsApplyingSchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FoundationEvidenceDocumentLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoverningBodyConsentEvidenceDocumentLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalAuthorityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectedPupilNumbersYear1")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectedPupilNumbersYear2")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectedPupilNumbersYear3")
                        .HasColumnType("int");

                    b.Property<bool?>("SchoolAdEqualitiesImpactAssessment")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolAdEqualitiesImpactAssessmentDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolAdFeederSchools")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolAdInspectedButReportNotPublished")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolAdInspectedReportNotPublishedExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolAdSafeguarding")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolAdSafeguardingExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolAdSchoolContributionToTrust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolAddFurtherInformation")
                        .HasColumnType("bit");

                    b.Property<bool?>("SchoolBuildLandFutureProgramme")
                        .HasColumnType("bit");

                    b.Property<bool?>("SchoolBuildLandGrants")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolBuildLandGrantsBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolBuildLandOwnerExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolBuildLandPFIScheme")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolBuildLandPFISchemeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolBuildLandPriorityBuildingProgramme")
                        .HasColumnType("bit");

                    b.Property<bool?>("SchoolBuildLandSharedFacilities")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolBuildLandSharedFacilitiesExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolBuildLandWorksPlanned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SchoolBuildLandWorksPlannedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchoolBuildLandWorksPlannedExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SchoolCFYCapitalForward")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SchoolCFYCapitalForwardStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolCFYCapitalIsDeficit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SchoolCFYEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SchoolCFYRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("SchoolCFYRevenueIsDeficit")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolCFYRevenueStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolCapacityAssumptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SchoolCapacityPublishedAdmissionsNumber")
                        .HasColumnType("int");

                    b.Property<bool?>("SchoolConsultationStakeholders")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolConsultationStakeholdersConsult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionApproverContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionApproverContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolConversionChangeName")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolConversionChangeNameValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactChairEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactChairName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactChairTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactHeadEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactHeadName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactHeadTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionContactRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionMainContactOtherEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionMainContactOtherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionMainContactOtherRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionMainContactOtherTelephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolConversionReasonsForJoining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SchoolConversionTargetDateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("SchoolConversionTargetDateDifferent")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolConversionTargetDateExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolDeclarationBodyAgree")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolDeclarationSignedByEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolDeclarationSignedById")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolDeclarationSignedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolDeclarationTeacherChair")
                        .HasColumnType("bit");

                    b.Property<bool?>("SchoolFaithSchool")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolFaithSchoolDioceseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolFinancialInvestigations")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolFinancialInvestigationsExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolFinancialInvestigationsTrustAware")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolFurtherInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolLaClosurePlans")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolLaClosurePlansExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolLaReorganization")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolLaReorganizationExplain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SchoolNFYCapitalForward")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SchoolNFYCapitalForwardStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolNFYCapitalIsDeficit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SchoolNFYEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SchoolNFYRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("SchoolNFYRevenueIsDeficit")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolNFYRevenueStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SchoolPFYCapitalForward")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SchoolPFYCapitalForwardStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolPFYCapitalIsDeficit")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SchoolPFYEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SchoolPFYRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("SchoolPFYRevenueIsDeficit")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolPFYRevenueStatusExplained")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolPartOfFederation")
                        .HasColumnType("bit");

                    b.Property<bool?>("SchoolSACREExemption")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SchoolSACREExemptionEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SchoolSupportGrantFundsPaidTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SchoolSupportedFoundation")
                        .HasColumnType("bit");

                    b.Property<string>("SchoolSupportedFoundationBodyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urn")
                        .HasColumnType("int");

                    b.HasKey("ApplyingSchoolId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("A2BApplicationApplyingSchool", "sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplicationKeyPersons", b =>
                {
                    b.Property<int>("KeyPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeyPersonId"), 1L, 1);

                    b.Property<string>("ApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("DynamicsKeyPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KeyPersonBiography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("KeyPersonCeoExecutive")
                        .HasColumnType("bit");

                    b.Property<bool?>("KeyPersonChairOfTrust")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KeyPersonDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("KeyPersonFinancialDirector")
                        .HasColumnType("bit");

                    b.Property<bool?>("KeyPersonMember")
                        .HasColumnType("bit");

                    b.Property<bool?>("KeyPersonOther")
                        .HasColumnType("bit");

                    b.Property<bool?>("KeyPersonTrustee")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KeyPersonId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("A2BApplicationKeyPersons", "sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BSchoolLease", b =>
                {
                    b.Property<int>("SchoolLeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolLeaseId"), 1L, 1);

                    b.Property<int>("ApplyingSchoolId")
                        .HasColumnType("int");

                    b.Property<Guid>("DynamicsSchoolLeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("SchoolLeaseInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SchoolLeasePaymentToDate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SchoolLeasePurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SchoolLeaseRepaymentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SchoolLeaseResponsibleForAssets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLeaseTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLeaseValueOfAssets")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolLeaseId");

                    b.HasIndex("ApplyingSchoolId");

                    b.ToTable("A2BSchoolLease", "sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BSchoolLoan", b =>
                {
                    b.Property<int>("SchoolLoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolLoanId"), 1L, 1);

                    b.Property<int>("ApplyingSchoolId")
                        .HasColumnType("int");

                    b.Property<Guid>("DynamicsSchoolLoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("SchoolLoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SchoolLoanInterestRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLoanProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLoanPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolLoanSchedule")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolLoanId");

                    b.HasIndex("ApplyingSchoolId");

                    b.ToTable("A2BSchoolLoan", "sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyTransferProjectIntendedTransferBenefits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FkAcademyTransferProjectId")
                        .HasColumnType("int")
                        .HasColumnName("fk_AcademyTransferProjectId");

                    b.Property<string>("SelectedBenefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkAcademyTransferProjectId");

                    b.ToTable("AcademyTransferProjectIntendedTransferBenefits", "sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyTransferProjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("AnyRisks")
                        .HasColumnType("bit");

                    b.Property<string>("AssignedUserEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedUserFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("BenefitsSectionIsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("ComplexLandAndBuildingFurtherSpecification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ComplexLandAndBuildingShouldBeConsidered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiocesanConsent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("EqualitiesImpactAssessmentConsidered")
                        .HasColumnType("bit");

                    b.Property<bool?>("FeatureSectionIsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("FinanceAndDebtFurtherSpecification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FinanceAndDebtShouldBeConsidered")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasHtbDate")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasTargetDateForTransfer")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasTransferFirstDiscussedDate")
                        .HasColumnType("bit");

                    b.Property<string>("HighProfileFurtherSpecification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HighProfileShouldBeConsidered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HtbDate")
                        .HasColumnType("date");

                    b.Property<string>("IncomingTrustAgreement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("LegalRequirementsSectionIsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("OtherBenefitValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherRisksFurtherSpecification")
                        .HasMaxLength(20000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OtherRisksShouldBeConsidered")
                        .HasColumnType("bit");

                    b.Property<string>("OtherTransferTypeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutgoingTrustConsent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutgoingTrustUkprn")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ProjectRationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("RationaleSectionIsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("RddOrEsfaIntervention")
                        .HasColumnType("bit");

                    b.Property<string>("RddOrEsfaInterventionDetail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TargetDateForTransfer")
                        .HasColumnType("date");

                    b.Property<DateTime?>("TransferFirstDiscussed")
                        .HasColumnType("date");

                    b.Property<string>("TrustSponsorRationale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfTransfer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR sdd.sequence_AcademyTransferProjectUrn");

                    b.Property<string>("WhoInitiatedTheTransfer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__AcademyT__C5B214360AF6201A");

                    b.HasIndex("Urn")
                        .HasDatabaseName("AcademyTransferProjectUrn");

                    b.ToTable("AcademyTransferProjects", "sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.FssProject", b =>
                {
                    b.Property<DateTime?>("ActualOpeningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AgeRange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationWave")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentFreeSchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfEntryIntoPreOpening")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSchoolClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FAActualCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FAForecastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FSGLeadContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaithStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaithType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreeSchoolPenPortrait")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeographicalRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KickOfMeetingHeldDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LaesTab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MemberOfParliament")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfFormsOfEntry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfPupil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nursery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherFaithType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProvisionalOpeningDateAgreedWithTrust")
                        .HasColumnType("datetime2");

                    b.Property<string>("RSCRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RealisticYearofOpening")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentialBoardingProvisionDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentialOrBoardingProvision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolPhase")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SixthForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SixthFormType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialism")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrustName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URN")
                        .HasColumnType("nvarchar(max)");

                    b.ToView("vw_Fss_ProjectData", "fsg");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.TransferringAcademies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FkAcademyTransferProjectId")
                        .HasColumnType("int")
                        .HasColumnName("fk_AcademyTransferProjectId");

                    b.Property<string>("IncomingTrustUkprn")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("KeyStage2PerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyStage4PerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeyStage5PerformanceAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LatestOfstedReportAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutgoingAcademyUkprn")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("PupilNumbersAdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkAcademyTransferProjectId");

                    b.ToTable("TransferringAcademies", "sdd");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplicationApplyingSchool", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.A2BApplication", "A2BApplication")
                        .WithMany("ApplyingSchools")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("A2BApplication");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplicationKeyPersons", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.A2BApplication", "A2BApplication")
                        .WithMany("KeyPersons")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("A2BApplication");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BSchoolLease", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.A2BApplicationApplyingSchool", "A2BApplicationApplyingSchool")
                        .WithMany("SchoolLeases")
                        .HasForeignKey("ApplyingSchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("A2BApplicationApplyingSchool");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BSchoolLoan", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.A2BApplicationApplyingSchool", "A2BApplicationApplyingSchool")
                        .WithMany("SchoolLoans")
                        .HasForeignKey("ApplyingSchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("A2BApplicationApplyingSchool");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyTransferProjectIntendedTransferBenefits", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.AcademyTransferProjects", "FkAcademyTransferProject")
                        .WithMany("AcademyTransferProjectIntendedTransferBenefits")
                        .HasForeignKey("FkAcademyTransferProjectId")
                        .HasConstraintName("FK__AcademyTr__fk_Ac__4316F928");

                    b.Navigation("FkAcademyTransferProject");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.TransferringAcademies", b =>
                {
                    b.HasOne("TramsDataApi.DatabaseModels.AcademyTransferProjects", "FkAcademyTransferProject")
                        .WithMany("TransferringAcademies")
                        .HasForeignKey("FkAcademyTransferProjectId")
                        .HasConstraintName("FK__Transferr__fk_Ac__403A8C7D");

                    b.Navigation("FkAcademyTransferProject");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplication", b =>
                {
                    b.Navigation("ApplyingSchools");

                    b.Navigation("KeyPersons");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.A2BApplicationApplyingSchool", b =>
                {
                    b.Navigation("SchoolLeases");

                    b.Navigation("SchoolLoans");
                });

            modelBuilder.Entity("TramsDataApi.DatabaseModels.AcademyTransferProjects", b =>
                {
                    b.Navigation("AcademyTransferProjectIntendedTransferBenefits");

                    b.Navigation("TransferringAcademies");
                });
#pragma warning restore 612, 618
        }
    }
}
