using System;

namespace TramsDataApi.RequestModels.ApplyToBecome
{
    public class A2BApplicationApplyingSchoolModel
    {
        public string UpdatedTrustFields { get; set; }
        public string SchoolDeclarationSignedById { get; set; }
        public bool? SchoolDeclarationBodyAgree { get; set; }
        public bool? SchoolDeclarationTeacherChair { get; set; }
        public string SchoolDeclarationSignedByEmail { get; set; }
        public string Name { get; set; }
        public string UpdatedSchoolFields { get; set; }
        public string SchoolConversionReasonsForJoining { get; set; }
        public bool? SchoolConversionTargetDateDifferent { get; set; }
        public DateTime? SchoolConversionTargetDateDate { get; set; }
        public string SchoolConversionTargetDateExplained { get; set; }
        public bool? SchoolConversionChangeName { get; set; }
        public string SchoolConversionChangeNameValue { get; set; }
        public string SchoolConversionContactHeadName { get; set; }
        public string SchoolConversionContactHeadEmail { get; set; }
        public string SchoolConversionContactHeadTel { get; set; }
        public string SchoolConversionContactChairName { get; set; }
        public string SchoolConversionContactChairEmail { get; set; }
        public string SchoolConversionContactChairTel { get; set; }
        public int? SchoolConversionMainContact { get; set; }
        public string SchoolConversionMainContactOtherName { get; set; }
        public string SchoolConversionMainContactOtherEmail { get; set; }
        public string SchoolConversionMainContactOtherTelephone { get; set; }
        public string SchoolConversionMainContactOtherRole { get; set; }
        public string SchoolConversionApproverContactName { get; set; }
        public string SchoolConversionApproverContactEmail { get; set; }
        public bool? SchoolAdInspectedButReportNotPublished { get; set; }
        public string SchoolAdInspectedReportNotPublishedExplain { get; set; }
        public bool? SchoolLaReorganization { get; set; }
        public string SchoolLaReorganizationExplain { get; set; }
        public bool? SchoolLaClosurePlans { get; set; }
        public string SchoolLaClosurePlansExplain { get; set; }
        public bool? SchoolPartOfFederation { get; set; }
        public bool? SchoolAddFurtherInformation { get; set; }
        public string SchoolFurtherInformation { get; set; }
        public string SchoolAdSchoolContributionToTrust { get; set; }
        public bool? SchoolAdSafeguarding { get; set; }
        public string SchoolAdSafeguardingExplained { get; set; }
        public bool? SchoolSACREExemption { get; set; }
        public DateTime? SchoolSACREExemptionEndDate { get; set; }
        public bool? SchoolFaithSchool { get; set; }
        public string SchoolFaithSchoolDioceseName { get; set; }
        public bool? SchoolSupportedFoundation { get; set; }
        public string SchoolSupportedFoundationBodyName { get; set; }
        public string SchoolAdFeederSchools { get; set; }
        public bool? SchoolAdEqualitiesImpactAssessment { get; set; }
        public double? SchoolPFYRevenue { get; set; }
        public string SchoolPFYRevenueStatus { get; set; }
        public string SchoolPFYRevenueStatusExplained { get; set; }
        public double? SchoolPFYCapitalForward { get; set; }
        public string SchoolPFYCapitalForwardStatus { get; set; }
        public string SchoolPFYCapitalForwardStatusExplained { get; set; }
        public double? SchoolCFYRevenue { get; set; }
        public string SchoolCFYRevenueStatus { get; set; }
        public string SchoolCFYRevenueStatusExplained { get; set; }
        public double? SchoolCFYCapitalForward { get; set; }
        public string SchoolCFYCapitalForwardStatus { get; set; }
        public string SchoolCFYCapitalForwardStatusExplained { get; set; }
        public double? SchoolNFYRevenue { get; set; }
        public string SchoolNFYRevenueStatus { get; set; }
        public string SchoolNFYRevenueStatusExplained { get; set; }
        public double? SchoolNFYCapitalForward { get; set; }
        public string SchoolNFYCapitalForwardStatus { get; set; }
        public string SchoolNFYCapitalForwardStatusExplained { get; set; }
        public bool? SchoolFinancialInvestigations { get; set; }
        public string SchoolFinancialInvestigationsExplain { get; set; }
        public bool? SchoolFinancialInvestigationsTrustAware { get; set; }
        public DateTime? SchoolNFYEndDate { get; set; }
        public DateTime? SchoolPFYEndDate { get; set; }
        public DateTime? SchoolCFYEndDate { get; set; }
        public bool? SchoolLoanExists { get; set; }
        public bool? SchoolLeaseExists { get; set; }
        public int? SchoolCapacityYear1 { get; set; }
        public int? SchoolCapacityYear2 { get; set; }
        public int? SchoolCapacityYear3 { get; set; }
        public string SchoolCapacityAssumptions { get; set; }
        public int? SchoolCapacityPublishedAdmissionsNumber { get; set; }
        public string SchoolBuildLandOwnerExplained { get; set; }
        public bool? SchoolBuildLandSharedFacilities { get; set; }
        public string SchoolBuildLandSharedFacilitiesExplained { get; set; }
        public bool? SchoolBuildLandWorksPlanned { get; set; }
        public string SchoolBuildLandWorksPlannedExplained { get; set; }
        public DateTime? SchoolBuildLandWorksPlannedDate { get; set; }
        public bool? SchoolBuildLandGrants { get; set; }
        public string SchoolBuildLandGrantsBody { get; set; }
        public bool? SchoolBuildLandPriorityBuildingProgramme { get; set; }
        public bool? SchoolBuildLandFutureProgramme { get; set; }
        public bool? SchoolBuildLandPFIScheme { get; set; }
        public string SchoolBuildLandPFISchemeType { get; set; }
        public bool? SchoolConsultationStakeholders { get; set; }
        public string SchoolConsultationStakeholdersConsult { get; set; }
        public int? SchoolSupportGrantFundsPaidTo { get; set; }
        public string SchoolDeclarationSignedByName { get; set; }
    }
}