using TramsDataApi.DatabaseModels;
using TramsDataApi.Enums;
using TramsDataApi.Extensions;
using TramsDataApi.RequestModels.ApplyToBecome;
using TramsDataApi.ResponseModels.ApplyToBecome;

namespace TramsDataApi.Factories.A2BApplicationFactories
{
    public static class A2BApplicationApplyingSchoolFactory
    {
        public static A2BApplicationApplyingSchool Create(A2BApplicationApplyingSchoolModel request)
        {
            return request == null
                ? null
                : new A2BApplicationApplyingSchool
                {
	                Name = request.Name,
                    UpdatedTrustFields = request.UpdatedTrustFields,
                    SchoolDeclarationSignedById = request.SchoolDeclarationSignedById,
                    SchoolDeclarationBodyAgree = request.SchoolDeclarationBodyAgree,
                    SchoolDeclarationTeacherChair = request.SchoolDeclarationTeacherChair,
                    SchoolDeclarationSignedByEmail = request.SchoolDeclarationSignedByEmail,
                    UpdatedSchoolFields = request.UpdatedSchoolFields,
                    SchoolConversionReasonsForJoining = request.SchoolConversionReasonsForJoining,
                    SchoolConversionTargetDateDifferent = request.SchoolConversionTargetDateDifferent,
                    SchoolConversionTargetDateDate = request.SchoolConversionTargetDateDate,
                    SchoolConversionTargetDateExplained = request.SchoolConversionTargetDateExplained,
                    SchoolConversionChangeName = request.SchoolConversionChangeName,
                    SchoolConversionChangeNameValue = request.SchoolConversionChangeNameValue,
                    SchoolConversionContactHeadName = request.SchoolConversionContactHeadName,
                    SchoolConversionContactHeadEmail = request.SchoolConversionContactHeadEmail,
                    SchoolConversionContactHeadTel = request.SchoolConversionContactHeadTel,
                    SchoolConversionContactChairName = request.SchoolConversionContactChairName,
                    SchoolConversionContactChairEmail = request.SchoolConversionContactChairEmail,
                    SchoolConversionContactChairTel = request.SchoolConversionContactChairTel,
                    SchoolConversionMainContact = request.SchoolConversionMainContact,
                    SchoolConversionMainContactOtherName = request.SchoolConversionMainContactOtherName,
                    SchoolConversionMainContactOtherEmail = request.SchoolConversionMainContactOtherEmail,
                    SchoolConversionMainContactOtherTelephone = request.SchoolConversionMainContactOtherTelephone,
                    SchoolConversionMainContactOtherRole = request.SchoolConversionMainContactOtherRole,
                    SchoolConversionApproverContactName = request.SchoolConversionApproverContactName,
                    SchoolConversionApproverContactEmail = request.SchoolConversionApproverContactEmail,
                    SchoolAdInspectedButReportNotPublished = request.SchoolAdInspectedButReportNotPublished,
                    SchoolAdInspectedReportNotPublishedExplain = request.SchoolAdInspectedReportNotPublishedExplain,
                    SchoolLaReorganization = request.SchoolLaReorganization,
                    SchoolLaReorganizationExplain = request.SchoolLaReorganizationExplain,
                    SchoolLaClosurePlans = request.SchoolLaClosurePlans,
                    SchoolLaClosurePlansExplain = request.SchoolLaClosurePlansExplain,
                    SchoolPartOfFederation = request.SchoolPartOfFederation,
                    SchoolAddFurtherInformation = request.SchoolAddFurtherInformation,
                    SchoolFurtherInformation = request.SchoolFurtherInformation,
                    SchoolAdSchoolContributionToTrust = request.SchoolAdSchoolContributionToTrust,
                    SchoolAdSafeguarding = request.SchoolAdSafeguarding,
                    SchoolAdSafeguardingExplained = request.SchoolAdSafeguardingExplained,
                    SchoolSACREExemption = request.SchoolSACREExemption,
                    SchoolSACREExemptionEndDate = request.SchoolSACREExemptionEndDate,
                    SchoolFaithSchool = request.SchoolFaithSchool,
                    SchoolFaithSchoolDioceseName = request.SchoolFaithSchoolDioceseName,
                    SchoolSupportedFoundation = request.SchoolSupportedFoundation,
                    SchoolSupportedFoundationBodyName = request.SchoolSupportedFoundationBodyName,
                    SchoolAdFeederSchools = request.SchoolAdFeederSchools,
                    SchoolAdEqualitiesImpactAssessment = request.SchoolAdEqualitiesImpactAssessment,
                    SchoolPFYRevenue = request.SchoolPFYRevenue,
                    SchoolPFYRevenueStatus = request.SchoolPFYRevenueStatus.ToSurplusDeficitEnum(),
                    SchoolPFYRevenueStatusExplained = request.SchoolPFYRevenueStatusExplained,
                    SchoolPFYCapitalForward = request.SchoolPFYCapitalForward,
                    SchoolPFYCapitalForwardStatus = request.SchoolPFYCapitalForwardStatus.ToSurplusDeficitEnum(),
                    SchoolPFYCapitalForwardStatusExplained = request.SchoolPFYCapitalForwardStatusExplained,
                    SchoolCFYRevenue = request.SchoolCFYRevenue,
                    SchoolCFYRevenueStatus = request.SchoolCFYRevenueStatus.ToSurplusDeficitEnum(),
                    SchoolCFYRevenueStatusExplained = request.SchoolCFYRevenueStatusExplained,
                    SchoolCFYCapitalForward = request.SchoolCFYCapitalForward,
                    SchoolCFYCapitalForwardStatus = request.SchoolCFYCapitalForwardStatus.ToSurplusDeficitEnum(),
                    SchoolCFYCapitalForwardStatusExplained = request.SchoolCFYCapitalForwardStatusExplained,
                    SchoolNFYRevenue = request.SchoolNFYRevenue,
                    SchoolNFYRevenueStatus = request.SchoolNFYRevenueStatus.ToSurplusDeficitEnum(),
                    SchoolNFYRevenueStatusExplained = request.SchoolNFYRevenueStatusExplained,
                    SchoolNFYCapitalForward = request.SchoolNFYCapitalForward,
                    SchoolNFYCapitalForwardStatus = request.SchoolNFYCapitalForwardStatus.ToSurplusDeficitEnum(),
                    SchoolNFYCapitalForwardStatusExplained = request.SchoolNFYCapitalForwardStatusExplained,
                    SchoolFinancialInvestigations = request.SchoolFinancialInvestigations,
                    SchoolFinancialInvestigationsExplain = request.SchoolFinancialInvestigationsExplain,
                    SchoolFinancialInvestigationsTrustAware = request.SchoolFinancialInvestigationsTrustAware,
                    SchoolNFYEndDate = request.SchoolNFYEndDate,
                    SchoolPFYEndDate = request.SchoolPFYEndDate,
                    SchoolCFYEndDate = request.SchoolCFYEndDate,
                    SchoolLoanExists = request.SchoolLoanExists,
                    SchoolLeaseExists = request.SchoolLeaseExists,
                    SchoolCapacityYear1 = request.SchoolCapacityYear1,
                    SchoolCapacityYear2 = request.SchoolCapacityYear2,
                    SchoolCapacityYear3 = request.SchoolCapacityYear3,
                    SchoolCapacityAssumptions = request.SchoolCapacityAssumptions,
                    SchoolCapacityPublishedAdmissionsNumber =  request.SchoolCapacityPublishedAdmissionsNumber,
                    SchoolBuildLandOwnerExplained = request.SchoolBuildLandOwnerExplained,
                    SchoolBuildLandSharedFacilities = request.SchoolBuildLandSharedFacilities,
                    SchoolBuildLandSharedFacilitiesExplained = request.SchoolBuildLandSharedFacilitiesExplained,
                    SchoolBuildLandWorksPlanned = request.SchoolBuildLandWorksPlanned,
                    SchoolBuildLandWorksPlannedExplained = request.SchoolBuildLandWorksPlannedExplained,
                    SchoolBuildLandWorksPlannedDate = request.SchoolBuildLandWorksPlannedDate,
                    SchoolBuildLandGrants = request.SchoolBuildLandGrants,
                    SchoolBuildLandGrantsBody = request.SchoolBuildLandGrantsBody,
                    SchoolBuildLandPriorityBuildingProgramme = request.SchoolBuildLandPriorityBuildingProgramme,
                    SchoolBuildLandFutureProgramme = request.SchoolBuildLandFutureProgramme,
                    SchoolBuildLandPFIScheme = request.SchoolBuildLandPFIScheme,
                    SchoolBuildLandPFISchemeType = request.SchoolBuildLandPFISchemeType,
                    SchoolConsultationStakeholders = request.SchoolConsultationStakeholders,
                    SchoolConsultationStakeholdersConsult = request.SchoolConsultationStakeholdersConsult,
                    SchoolSupportGrantFundsPaidTo = request.SchoolSupportGrantFundsPaidTo,
                    SchoolDeclarationSignedByName = request.SchoolDeclarationSignedByName
                };
        }

        // CML - casting nullables into non-nullables in the code below for now
        // will throw InvalidOperationException if value is null
        public static A2BApplyingSchoolResponse Create(A2BApplicationApplyingSchool request)
	    { 
		    return request is null ? null : new A2BApplyingSchoolResponse
		    {	
					SchoolName = request.Name,
                //UpdatedTrustFields = request.UpdatedTrustFields,
                //SchoolDeclarationSignedById = request.SchoolDeclarationSignedById,
                SchoolApplicantDeclarationIsApplicationCorrect = request.SchoolDeclarationBodyAgree,
                //SchoolDeclarationTeacherChair = request.SchoolDeclarationTeacherChair,
                //SchoolDeclarationSignedByEmail = request.SchoolDeclarationSignedByEmail,
                //UpdatedSchoolFields = request.UpdatedSchoolFields,
                //SchoolConversionReasonsForJoining = request.SchoolConversionReasonsForJoining,
                    SchoolConversionTargetDateSpecified = request.SchoolConversionTargetDateDifferent,
                    SchoolConversionTargetDate = request.SchoolConversionTargetDateDate,
                    SchoolConversionTargetDateExplained = request.SchoolConversionTargetDateExplained,
                    SchoolConversionChangeNamePlanned = request.SchoolConversionChangeName,
                    SchoolConversionProposedNewSchoolName = request.SchoolConversionChangeNameValue,
                    SchoolConversionContactHeadName = request.SchoolConversionContactHeadName,
                    SchoolConversionContactHeadEmail = request.SchoolConversionContactHeadEmail,
                    SchoolConversionContactHeadTel = request.SchoolConversionContactHeadTel,
                    SchoolConversionContactChairName = request.SchoolConversionContactChairName,
                    SchoolConversionContactChairEmail = request.SchoolConversionContactChairEmail,
                    SchoolConversionContactChairTel = request.SchoolConversionContactChairTel,
                    MainContactForApplication = request.SchoolConversionMainContact.MapIntToContactType(), // enum "headteacher", "chair of governing body", "someone else"
                    SchoolConversionMainContactOtherName = request.SchoolConversionMainContactOtherName,
                    SchoolConversionMainContactOtherEmail = request.SchoolConversionMainContactOtherEmail,
                    SchoolConversionMainContactOtherTelephone = request.SchoolConversionMainContactOtherTelephone,
                    SchoolConversionMainContactOtherRole = request.SchoolConversionMainContactOtherRole,
                    SchoolConversionApproverContactName = request.SchoolConversionApproverContactName,
                    SchoolConversionApproverContactEmail = request.SchoolConversionApproverContactEmail,
                    SchoolAdInspectedButReportNotPublished = request.SchoolAdInspectedButReportNotPublished,
                //                    SchoolAdInspectedReportNotPublishedExplain = request.SchoolAdInspectedReportNotPublishedExplain,
                    SchoolPartOfLaReorganizationPlan = request.SchoolLaReorganization,
                SchoolLaReorganizationDetails = request.SchoolLaReorganizationExplain,
                SchoolPartOfLaClosurePlan = request.SchoolLaClosurePlans,
                SchoolLaClosurePlanDetails = request.SchoolLaClosurePlansExplain,
                SchoolIsPartOfFederation = request.SchoolPartOfFederation,
                SchoolAdditionalInformationAdded = request.SchoolAddFurtherInformation,
                SchoolAdditionalInformation = request.SchoolFurtherInformation,
                SchoolAdSchoolContributionToTrust = request.SchoolAdSchoolContributionToTrust,
                SchoolOngoingSafeguardingInvestigations = request.SchoolAdSafeguarding,
                SchoolOngoingSafeguardingDetails = request.SchoolAdSafeguardingExplained,
                SchoolHasSACREException = request.SchoolSACREExemption,
                    SchoolSACREExemptionEndDate = request.SchoolSACREExemptionEndDate,
                    SchoolFaithSchool = request.SchoolFaithSchool,
                    SchoolFaithSchoolDioceseName = request.SchoolFaithSchoolDioceseName,
                SchoolIsSupportedByFoundation = request.SchoolSupportedFoundation,
                    SchoolSupportedFoundationBodyName = request.SchoolSupportedFoundationBodyName,
                    SchoolAdFeederSchools = request.SchoolAdFeederSchools,
                SchoolAdEqualitiesImpactAssessmentCompleted = request.SchoolAdEqualitiesImpactAssessment,
                    PreviousFinancialYear = new FinancialYear
                    {
                        RevenueCarryForward = (decimal)request.SchoolPFYRevenue,
                        RevenueStatus = request.SchoolPFYRevenueStatus.ToSurplusDeficitString(),
                        RevenueStatusExplained = request.SchoolPFYRevenueStatusExplained,
                        CapitalCarryForward = (decimal)request.SchoolPFYCapitalForward,
                        CapitalStatus = request.SchoolPFYCapitalForwardStatus.ToSurplusDeficitString(),
                        CapitalStatusExplained = request.SchoolPFYCapitalForwardStatusExplained,
                        FYEndDate = request.SchoolPFYEndDate
                    },
                    CurrentFinancialYear = new FinancialYear
                    {
                        RevenueCarryForward = (decimal)request.SchoolCFYRevenue,
                        RevenueStatus = request.SchoolCFYRevenueStatus.ToSurplusDeficitString(),
                        RevenueStatusExplained = request.SchoolCFYRevenueStatusExplained,
                        CapitalCarryForward = (decimal)request.SchoolCFYCapitalForward,
                        CapitalStatus = request.SchoolCFYCapitalForwardStatus.ToSurplusDeficitString(),
                        CapitalStatusExplained = request.SchoolCFYCapitalForwardStatusExplained,
                        FYEndDate = request.SchoolCFYEndDate
                    },
                NextFinancialYear = new FinancialYear
                {
                    RevenueCarryForward = (decimal)request.SchoolNFYRevenue,
                    RevenueStatus = request.SchoolNFYRevenueStatus.ToSurplusDeficitString(),
                    RevenueStatusExplained = request.SchoolNFYRevenueStatusExplained,
                    CapitalCarryForward = (decimal)request.SchoolNFYCapitalForward,
                    CapitalStatus = request.SchoolNFYCapitalForwardStatus.ToSurplusDeficitString(),
                    CapitalStatusExplained = request.SchoolNFYCapitalForwardStatusExplained,
                    FYEndDate = request.SchoolNFYEndDate
                },
                FinanceOngoingInvestigations = request.SchoolFinancialInvestigations,
                    SchoolFinancialInvestigationsExplain = request.SchoolFinancialInvestigationsExplain,
                    SchoolFinancialInvestigationsTrustAware = request.SchoolFinancialInvestigationsTrustAware,
                //SchoolLoanExists = request.SchoolLoanExists, // remove? just use whether it's an empty list?
                //SchoolLeaseExists = request.SchoolLeaseExists, // remove? just use whether it's an empty list?
                SchoolCapacityYear1 = (int)request.SchoolCapacityYear1,
                    SchoolCapacityYear2 = (int)request.SchoolCapacityYear2,
                    SchoolCapacityYear3 = (int)request.SchoolCapacityYear3,
                    SchoolCapacityAssumptions = request.SchoolCapacityAssumptions,
                    SchoolCapacityPublishedAdmissionsNumber = (int)request.SchoolCapacityPublishedAdmissionsNumber,
                    SchoolBuildLandOwnerExplained = request.SchoolBuildLandOwnerExplained,
                    SchoolBuildLandSharedFacilities = request.SchoolBuildLandSharedFacilities,
                    SchoolBuildLandSharedFacilitiesExplained = request.SchoolBuildLandSharedFacilitiesExplained,
                    SchoolBuildLandWorksPlanned = request.SchoolBuildLandWorksPlanned,
                    SchoolBuildLandWorksPlannedExplained = request.SchoolBuildLandWorksPlannedExplained,
                SchoolBuildLandWorksPlannedCompletionDate = request.SchoolBuildLandWorksPlannedDate,
                    SchoolBuildLandGrants = request.SchoolBuildLandGrants,
//                    SchoolBuildLandGrantsBody = request.SchoolBuildLandGrantsBody,
                    SchoolBuildLandPriorityBuildingProgramme = request.SchoolBuildLandPriorityBuildingProgramme,
                    SchoolBuildLandFutureProgramme = request.SchoolBuildLandFutureProgramme,
                    SchoolBuildLandPFIScheme = request.SchoolBuildLandPFIScheme,
                    SchoolBuildLandPFISchemeType = request.SchoolBuildLandPFISchemeType,
                SchoolHasConsultedStakeholders = request.SchoolConsultationStakeholders,
                SchoolPlanToConsultStakeholders = request.SchoolConsultationStakeholdersConsult,
                    SchoolSupportGrantFundsPaidTo = request.SchoolSupportGrantFundsPaidTo.ToSchoolTrustEnum(),
                    SchoolDeclarationSignedByName = request.SchoolDeclarationSignedByName
		    };
	    }
    }
}