name: Deploy to environment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Choose an environment to deploy to"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.environment }}

jobs:
  set-env:
    name: Determine environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.var.outputs.environment }}
      branch: ${{ steps.var.outputs.branch }}
      release: ${{ steps.var.outputs.release }}
      checked-out-sha: ${{ steps.var.outputs.checked-out-sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name for push/dispatch event
        run: |
          GIT_REF=${{ github.ref_name }}
          echo "branch_ref=${GIT_REF}" >> $GITHUB_ENV

      - id: var
        run: |
          GIT_REF=${{ env.branch_ref }}
          GIT_BRANCH=${GIT_REF##*/}
          INPUT=${{ github.event.inputs.environment }}
          ENVIRONMENT=${INPUT:-"development"}
          CHECKED_OUT_SHA="$(git log -1 '--format=format:%H')"
          RELEASE=${ENVIRONMENT,,}-`date +%Y-%m-%d`.${{ github.run_number }}
          echo "environment=${ENVIRONMENT,,}" >> $GITHUB_OUTPUT
          echo "branch=$GIT_BRANCH" >> $GITHUB_OUTPUT
          echo "checked-out-sha=${CHECKED_OUT_SHA}" >> $GITHUB_OUTPUT
          echo "release=${RELEASE}" >> $GITHUB_OUTPUT

  deploy-image:
    permissions:
      id-token: write
      contents: read
      packages: write
    name: Deploy '${{ needs.set-env.outputs.branch }}' to ${{ needs.set-env.outputs.environment }}
    needs: [ set-env ]
    uses: DFE-Digital/deploy-azure-container-apps-action/.github/workflows/build-push-deploy.yml@v3.0.0
    strategy:
        matrix:
          image: [
            "Dockerfile",
            "Dockerfile.PersonsApi"
          ]
          include:
            - image: "Dockerfile"
              aca_name: "ACA_CONTAINERAPP_NAME"
              prefix: ""
              name: "tramsapi-app"
            - image: "Dockerfile.PersonsApi"
              aca_name: "ACA_CONTAINERAPP_PERSONS_API_NAME"
              prefix: "persons-api-"
              name: "personsapi-app"
    with:
      docker-image-name: '${{ matrix.name }}'
      docker-build-file-name: './${{ matrix.image }}'
      docker-tag-prefix: ${{ matrix.prefix }}
      environment: ${{ needs.set-env.outputs.environment }}
      # Only annotate the release once, because both apps are deployed at the same time
      annotate-release: ${{ matrix.name == 'tramsapi-app' }}
      docker-build-args: |
        COMMIT_SHA="${{ needs.set-env.outputs.checked-out-sha }}"
        CI=true
    secrets:
      azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure-acr-client-id: ${{ secrets.ACR_CLIENT_ID }}
      azure-acr-name: ${{ secrets.ACR_NAME }}
      azure-aca-client-id: ${{ secrets.ACA_CLIENT_ID }}
      azure-aca-name: ${{ secrets.[matrix.aca_name] }}
      azure-aca-resource-group: ${{ secrets.ACA_RESOURCE_GROUP }}

  create-tag:
    name: Tag and release
    needs: set-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Create tag
        run: |
          git tag ${{ needs.set-env.outputs.release }}
          git push origin ${{ needs.set-env.outputs.release }}

      - name: Create release
        uses: "actions/github-script@v7"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              await github.rest.repos.createRelease({
                draft: ${{ needs.set-env.outputs.environment == 'test' }},
                generate_release_notes: true,
                name: "${{ needs.set-env.outputs.release }}",
                owner: context.repo.owner,
                prerelease: ${{ needs.set-env.outputs.environment == 'test' }},
                repo: context.repo.repo,
                tag_name: "${{ needs.set-env.outputs.release }}",
              });
            } catch (error) {
              core.setFailed(error.message);
            }

  cypress-tests:
    name: Run Cypress Tests
    needs: [ deploy-image, set-env ]
    if: needs.set-env.outputs.environment == 'test' || needs.set-env.outputs.environment == 'development'
    uses: ./.github/workflows/cypress-tests.yml
    with:
      environment: ${{ needs.set-env.outputs.environment }}
    secrets:
      TRAMS_API_KEY: ${{ secrets.TRAMS_API_KEY }}
      TRAMS_API_BASE_URL: ${{ secrets.TRAMS_API_BASE_URL }}
