name: Cypress test linting

on:
  pull_request:
    paths:
      - CypressTests
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CypressTests
    steps:
      - name: checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: lint cypress tests
        run: |
          npm ci
          npm run lint
