name: Continuous Integration / Terraform

on:
  push:
    branches: main
    paths:
      - 'terraform/**.tf'
  pull_request:
    paths:
      - 'terraform/**.tf'

jobs:
  continuous-integration-terraform:
    name: Continuous Integration Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Terraform Validate
        uses: DFE-Digital/terraform-linting-actions/.github/actions/validate@2608ca06a7f06e1869364c028a8d035d23627acc # v1.2.1
        with:
          entrypoint: ./terraform
          terraform_version: 1.9.8
