name: k6 Performance benchmark tests

on:
  workflow_dispatch:
    inputs:
        environment:
          type: environment
          description: "Choose an environment to run against"
          required: true

jobs:
  run-k6-tests:
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'development' || github.event.inputs.environment == 'test'
    defaults:
      run:
        working-directory: Dfe.Academies.Performance/scripts
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run k6 test
        uses: grafana/k6-action@e4714b734f2b0afaabeb7b4a69142745548ab9ec # v0.3.1
        with:
          filename: suite.js
        env:
          BASE_URL: ${{ secrets.TRAMS_API_BASE_URL }}
          API_KEY: ${{ secrets.TRAMS_API_KEY }}

      - name: Upload report
        if: ${{ success() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: summary
          path: summary.html