name: Security scanner tests

on:
  push:
    branches:
      - owasp-zap-ci
  workflow_dispatch:
  workflow_run:
    workflows: [Continuous delivery (development)]
    types:
      - completed

jobs:
  run-tests-with-zap:
    name: Run Cypress tests with OWASP ZAP
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare environment
        run: |
          echo "API_KEY=${{ secrets.TRAMS_API_KEY }}" >> $GITHUB_ENV
          echo "URL=${{ secrets.TRAMS_API_BASE_URL }}" >> $GITHUB_ENV
          echo "HTTP_PROXY=http://zap:8080" >> $GITHUB_ENV
          echo "NO_PROXY=zap,*.gvt1.com" >> $GITHUB_ENV
          echo "ZAP_API_KEY=${{ secrets.ZAP_API_KEY }}" >> $GITHUB_ENV

      - name: run tests with scanner
        run: |
          docker compose -f CypressTests/docker-compose.yml up --exit-code-from cypress

      - uses: actions/upload-artifact@v1
        with:
          name: report.html
          path: ./CypressTests/ZAP-Report.html
