name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: 'mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04'
        ports:
          - 1433:1433/tcp
        env:
          ACCEPT_EULA: 'Y'
          SA_PASSWORD: 'StrongPassword905'

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
