name: Build and run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: 'ghcr.io/dfe-digital/trams-development-database:latest'
        ports:
          - 1433:1433/tcp

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301'
    - name: Install EF for tests
      run: dotnet tool install --global dotnet-ef --version 6.0.5
    - name: Restore tools for tests
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
